[package]
name = "smtbr_gui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
dotext = "0.1.1"
regex = "1.9.0"
rand = "0.8.0"

[build-dependencies]
slint-build = "1.6"
