import { StandardButton, Button, VerticalBox, ProgressIndicator } from "std-widgets.slint";

component NewbiePage {
    in property <bool> is_yml: false;
    in-out property <bool> processing: false;
    in property <bool> is_error: false;
    callback serialize;
    callback tomain;

    if (!is_yml && !processing) :
        VerticalBox {
            Text {
                text: "Welcome to SMTBR, a Strategy Management Test Bank study helper with problem Randomization.\n Since it's the first time you're using SMTBR, data transformation works are needed.";
            }
            Text {
                text: "Are your test bank docx files ready?";
            }
            StandardButton {
                kind: yes;
                clicked => {root.processing = true;}
            }
            // StandardButton {
            //     kind: no;
            //     clicked => {}
            // }
        }
    if (!is_yml && processing) : 
        VerticalBox{
            ProgressIndicator {indeterminate: true;}
            Text {text: "processing...";
                init => {root.serialize();}}
        }
    if (is_error) : Text { text : "Error occurred!"; }
    if (is_yml) :
        VerticalBox {
            Text {
                text: "Successfully processed test bank files.";
            }
            Button {
                text: "Go to main menu";
                clicked => { root.tomain(); }
            }

        }
}

component HelpPage {
    callback tomain;

    VerticalBox {
        Text {
            text: "You can read the manual from: https://git.sr.ht/~czukay2019/smtbr";
        }
        Button {
            text: "Go back to main menu";
            clicked => { root.tomain(); }
        }
    }
}

component ContactPage {
    callback tomain;

    VerticalBox {
        Text {
            text: "Email me: czukay2019@proton.me";
        }
        Button {
            text: "Go back to main menu";
            clicked => { root.tomain(); }
        }
    }
}

component MainMenu {
    callback navigate;
    callback close;
    callback reset;
    
    out property <int> next_page: 1;

    VerticalBox {
        Text {
            text: "Welcome to SMTBR!";
        }
        Button {
            text: "Study -> Midterm Exam";
        }
        Button {
            text: "Study -> Final Exam";
        }
        Button {
            text: "Study -> All";
        }
        Button {
            text: "Manage Blacklist";
        }
        Button {
            text: "Quit";
            clicked => { root.close(); }
        }
        Button {
            text: "Help";
            clicked => { root.next_page = 4; root.navigate(); }
        }
        Button {
            text: "Factory Reset";
            clicked => {
                root.reset();
                root.next_page = 0; root.navigate();
            }
        }
        Button {
            text: "Contact Developer";
            clicked => { root.next_page = 5; root.navigate(); }
        }
    }
}
export component MainWindow inherits Window {
    // page enums:
    //     0 -> newbie page
    //     1 -> main page
    //     2 -> study page
    //     3 -> blacklist page
    //     4 -> help page
    //     5 -> contact info page
    title: "SMTBR";
    width: 400px;
    height: 500px;

    callback close();
    callback serialize();
    callback reset();
    in-out property <int> page_enum: 0;
    in-out property <bool> is_yaml: false;
    in-out property <bool> processing: false;
    in-out property <bool> is_error: false;

    if (self.page_enum == 0) : NewbiePage {
        width: 100%;
        is_yml: root.is_yaml;
        processing: root.processing;
        is_error: root.is_error;
        
        serialize => {root.serialize()}
        tomain => {
            root.page_enum = 1; 
            root.is_yaml = false; root.processing = false; root.is_error = false;
        }
    }
    if (self.page_enum == 1) : MainMenu {
        navigate => {root.page_enum = self.next_page}
        close => {root.close()}
        reset => {root.reset()}
    }
    if (self.page_enum == 4) : HelpPage {
        tomain => {root.page_enum = 1}
    }
    if (self.page_enum == 5) : ContactPage {
        tomain => {root.page_enum = 1}
    }

}
